# Generated by Django 4.1.2 on 2022-11-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=128)),
                ('Username', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passw', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_id', models.IntegerField(unique=True)),
                ('Article_Content', models.TextField()),
                ('Date_Posted', models.DateTimeField(auto_now_add=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_id', models.IntegerField(unique=True)),
                ('Comment_Username', models.CharField(max_length=16, unique=True)),
                ('Comment', models.TextField()),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Articles_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.IntegerField()),
                ('Re_Posts', models.PositiveIntegerField()),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.articles')),
                ('Post_Comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.comments')),
            ],
        ),
    ]
